### ISSUE TITLE
Out of Memory - OOM

### ISSUE THREAD

**Issue by ArcherEmiya05** [marlonlom/timeago#46] opened 2022-07-20 07:35 UTC
Using v4.0.1 we are getting this issue on an emulator device in a cloud.

```
java.lang.OutOfMemoryError: Failed to allocate a 64524 byte allocation with 62000 free bytes and 60KB until OOM
	at java.util.Arrays.copyOf(Arrays.java:3256)
	at sun.misc.IOUtils.readFully(IOUtils.java:60)
	at java.util.jar.JarFile.getBytes(JarFile.java:395)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:187)
	at java.util.jar.JarFile.getInputStream(JarFile.java:431)
	at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
	at java.net.URL.openStream(URL.java:1057)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:979)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2603)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2589)
	at java.security.AccessController.doPrivileged(AccessController.java:67)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2587)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1438)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1402)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1356)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1356)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1298)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:723)
	at com.github.marlonlom.utilities.timeago.TimeAgoMessages$Builder.defaultLocale(TimeAgoMessages.kt:125)
	at com.github.marlonlom.utilities.timeago.TimeAgo$Companion.using$default(TimeAgo.kt:249)
	at com.github.marlonlom.utilities.timeago.TimeAgo.using(TimeAgo.kt:0)
```

Any suggested solution for this? Thanks a lot

**Comment by marlonlom** [comment] 2024-02-13 03:16
Closing the issue because its not reproducible.
If in newer versions the problem persists, create a new issue, with more detailed information about the `java.lang.OutOfMemoryError`.

**Closed by marlonlom** 2024-02-13 03:16 UTC
Labels: wontfix
